stages:
  - build
  - test

buildCuda:win:
  stage: build
  script:
    - "&tools\\build.bat"
  artifacts:
    paths:
      - build/parament.exe
      - build/parament.dll

buildDocs:
  stage: build
  script:
    - "&tools\\buildDocs.bat"
  artifacts:
    paths:
      - docs/_build/

buildPyparament:win:
  stage: build
  script:
    - "&tools\\buildPyparament.bat"
  artifacts:
    paths:
      - src/dist/*.whl
      - src/dist/parament-*.tar.gz

runTest:win:
  stage: test
  script:
    - ".\\build\\parament.exe"
  dependencies:
    - buildCuda:win

runTestPyparament:win:
  stage: test
  script:
    - "&tools\\runTestPyparament.bat"
  dependencies:
    - buildPyparament:win
  artifacts:
    reports:
      junit: report.xml
