PARAMENT_STATUS_SUCCESS = 0
PARAMENT_STATUS_HOST_ALLOC_FAILED = 10
PARAMENT_STATUS_DEVICE_ALLOC_FAILED = 20
PARAMENT_STATUS_CUBLAS_INIT_FAILED = 30
PARAMENT_STATUS_INVALID_VALUE = 50
PARAMENT_STATUS_CUBLAS_FAILED = 60
PARAMENT_STATUS_SELECT_SMALLER_DT = 70
PARAMENT_FAIL = 1000
