# Error codes
PARAMENT_STATUS_SUCCESS = 0
PARAMENT_STATUS_HOST_ALLOC_FAILED = 10
PARAMENT_STATUS_DEVICE_ALLOC_FAILED = 20
PARAMENT_STATUS_CUBLAS_INIT_FAILED = 30
PARAMENT_STATUS_INVALID_VALUE = 50
PARAMENT_STATUS_CUBLAS_FAILED = 60
PARAMENT_STATUS_SELECT_SMALLER_DT = 70
PARAMENT_STATUS_NO_HAMILTONIAN = 80
PARAMENT_STATUS_INVALID_QUADRATURE_SELECTION = 90
PARAMENT_FAIL = 1000

# Quadrature mode
PARAMENT_QUADRATURE_NONE = 0x00000000
PARAMENT_QUADRATURE_MIDPOINT = 0x01000000
PARAMENT_QUADRATURE_SIMPSON = 0x02000000
