# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.1
        id: cuda-toolkit
        with:
          cuda: '11.2.2'
      
      - run: |
          echo "Installed cuda version is ${{steps.cuda-toolkit.outputs.cuda}}"
          echo "Cuda install location ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build parament
        run: |
          ./tools/build.sh
          
