# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Run pyparament test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Kaggle
        uses: joelhanson/kaggle-kernel-actions
        with:
          kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
          kaggle_key: ${{ secrets.KAGGLE_KEY }}
          kaggle_make_new_kernel: true
          kernel_id: polwelter/parament-testsuite-foobar
          code_file_path: Parament_colab_test.ipynb
          kernel_title: Parament test suite
          language: python
          kernel_type: notebook
          is_private: true
          enable_gpu: true
          enable_internet: true
          collect_output: true
      - name: Download outputs
        uses: actions/upload-artifact@v1
        with:
          name: outputs
          path: outputs/outputs.zip
