# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Run pyparament test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Kaggle
        uses: Joel-hanson/kaggle-kernel-actions@V1
        with:
          kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
          kaggle_key: ${{ secrets.KAGGLE_KEY }}
          kaggle_metadata_path: kernel-metadata.json
          kernel_id: polwelter/parament-testsuite-foobar
          kaggle_make_new_kernel: true
          collect_output: true
          
      - name: Show Tree
        run: |
          tree
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: outputs/report_test.xml
      - name: Download outputs
        uses: actions/upload-artifact@v1
        with:
          name: outputs
          path: outputs/outputs.zip
