name: PyPI-release

# Controls when the action will run.
on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: pip install wheel twine
      - name: Build sdist
        run: |
          cd src/
          python setup.py sdist --dist-dir ../dist
      - run: twine check ./dist/* --strict
      - name: Publish Python distribution to TestPyPI
        if: ${{ github.event.release.prerelease }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
      - name: Publish Python distribution to PyPI
        if: ${{ !github.event.release.prerelease }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
